#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

PYTHON_BIN="${PYTHON_BIN:-./.venv/bin/python}"
STATEMENT_COVERAGE_MIN="${STATEMENT_COVERAGE_MIN:-95}"
BRANCH_COVERAGE_MIN="${BRANCH_COVERAGE_MIN:-85}"
REPORT_DIR="${REPORT_DIR:-reports/coverage}"

export PYTHONPATH="services/_shared:services/nex-oa:services/nex-ag:services/nex-ae-api:services/nex-cx:services/nex-mo:providers/nex-compatible-provider:scripts/db:scripts/dev:scripts/smoke:scripts/quality${PYTHONPATH:+:$PYTHONPATH}"

mkdir -p "$REPORT_DIR"

"$PYTHON_BIN" -m pytest \
  --cov=services \
  --cov=scripts \
  --cov=providers \
  --cov-branch \
  --cov-report=term-missing \
  --cov-report="json:$REPORT_DIR/coverage.json" \
  --junitxml="$REPORT_DIR/junit.xml" \
  "$@"

"$PYTHON_BIN" scripts/quality/check_coverage_thresholds.py \
  "$REPORT_DIR/coverage.json" \
  "$STATEMENT_COVERAGE_MIN" \
  "$BRANCH_COVERAGE_MIN"

"$PYTHON_BIN" scripts/quality/validate_contracts.py

"$PYTHON_BIN" scripts/smoke/run_ae_web_static_browser_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_retrieval_quality_warning_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_grounded_response_quality_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_fetch_mode_protected_smoke_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_fetch_mode_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_traceable_mock_flow.py --summary
"$PYTHON_BIN" scripts/smoke/run_generation_recovery_mock_flow.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operations_dashboard_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_generation_quality_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_generation_quality_disposition_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_generation_remediation_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_generation_remediation_dashboard_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_remediation_execution_dispatch_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_remediation_execution_status_sync_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_remediation_execution_status_sync_worker_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_job_control_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_service_log_retention_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_service_log_retention_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/check_local_live_provider_config.py --summary
"$PYTHON_BIN" scripts/smoke/run_protected_remote_provider_live_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_dgx_process_dtype_probe.py --summary
"$PYTHON_BIN" scripts/smoke/run_protected_live_rag_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_protected_live_rag_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_protected_live_rag_score_sample_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_postgres_jobqueue_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_postgres_job_replay_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_postgres_operational_event_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_postgres_service_log_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_postgres_service_log_retention_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_postgres_service_log_retention_http_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_postgres_operations_smoke_pack.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_retrieval_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_upload_ownership_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_upload_duplicate_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_document_library_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_document_detail_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_document_detail_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_session_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_user_login_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_oa_auth_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_credential_login_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_generation_feedback_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_repaired_response_handoff_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_repaired_response_decision_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_repaired_response_decision_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_repaired_response_review_diagnostics_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_credential_login_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_credential_login_browser_operator_profile.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_same_origin_runtime_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_playwright_readiness.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_credential_login_playwright_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_post_login_document_workflow_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_source_file_materialization_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_authenticated_upload_fetch_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_authenticated_upload_playwright_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_uploaded_source_extraction_readiness_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_source_file_reader_fallback_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_uploaded_source_extraction_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_extractor_backend_gap_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_real_document_extraction_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_real_document_processing_pipeline_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_credential_login_browser_execution_readiness.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_credential_login_browser_live_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_credential_login_browser_postgres_evidence_hardening.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_credential_login_browser_smoke_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_credential_login_browser_harness_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_retrieval_package_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_retrieval_threshold_decision_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_processing_postgres_jobqueue_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_processing_postgres_event_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_processing_postgres_persistence_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_processing_postgres_api_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_cx_processing_run_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_cross_service_observability_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_postgres_test_smoke_suite.py --summary
"$PYTHON_BIN" scripts/smoke/run_s34_feedback_disposition_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_s35_remediation_observability_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_s36_remediation_execution_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_s37_remediation_runtime_integration_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_s38_remediation_operations_automation_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_s39_repaired_response_handoff_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_s40_ae_web_repaired_response_review_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_runtime_persistence_storage_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_chat_artifact_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s41_artifact_runtime_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_artifact_surface_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_artifact_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_artifact_playwright_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_artifact_multiformat_playwright_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_artifact_library_playwright_postgres_smoke.py --summary
node apps/nex-ae-web/scripts/runArtifactDeliveryAccessibilitySmoke.mjs --summary
node apps/nex-ae-web/scripts/runGroundedGenerationExperienceSmoke.mjs --summary
npm test --prefix apps/nex-ae-web
"$PYTHON_BIN" scripts/smoke/run_s42_ae_web_artifact_experience_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_export_transform_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_export_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s43_ae_artifact_export_transform_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_artifact_delivery_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_s44_ae_web_artifact_delivery_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_library_management_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_collection_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s45_ae_artifact_library_management_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_lifecycle_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_purge_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_candidate_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_batch_plan_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_purge_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s47_ae_artifact_retention_purge_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_history_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_history_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_history_query_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s48_ae_artifact_retention_history_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_scheduled_operations_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_scheduled_execution_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_scheduled_worker_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s49_ae_artifact_retention_scheduled_operations_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_scheduler_runtime_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_ag_artifact_retention_scheduler_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s50_ae_artifact_retention_scheduler_runtime_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_automation_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_artifact_retention_automation_operations_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_scheduler_tick_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_scheduler_tick_once_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_scheduler_daemon_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_ag_artifact_retention_scheduler_daemon_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_scheduler_daemon_one_cycle_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_scheduler_daemon_bounded_loop_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_scheduler_daemon_cli_execution_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_ag_artifact_retention_scheduler_daemon_run_read_model_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_ag_artifact_retention_scheduler_daemon_supervisor_read_model_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_physical_purge_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s51_ae_artifact_retention_automation_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_scheduler_daemon_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_s52_ae_scheduler_daemon_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_scheduler_daemon_operations_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_scheduler_daemon_operator_runbook_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_s53_ag_scheduler_daemon_operations_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_scheduler_daemon_runtime_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_s54_ae_scheduler_daemon_runtime_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_scheduler_daemon_process_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_s55_ae_scheduler_daemon_process_lifecycle_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_scheduler_daemon_executable_runtime_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_s56_ae_scheduler_daemon_executable_runtime_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_scheduler_daemon_supervisor_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_scheduler_daemon_supervisor_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s57_ae_scheduler_daemon_supervisor_operations_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_supervised_daemon_process_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_scheduler_daemon_supervised_process_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_ag_artifact_retention_scheduler_daemon_supervised_process_read_model_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s58_ae_scheduler_daemon_supervised_process_activation_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_supervised_process_operator_control_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_scheduler_daemon_operator_control_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_ag_artifact_retention_scheduler_daemon_operator_control_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s59_ae_supervised_process_operator_control_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_operator_control_execution_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_scheduler_daemon_operator_control_execution_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_ag_artifact_retention_scheduler_daemon_operator_control_execution_read_model_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s60_ae_operator_control_execution_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_operator_control_execution_worker_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_retention_scheduler_daemon_operator_control_execution_worker_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_operator_control_execution_worker_result_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_ag_artifact_retention_scheduler_daemon_operator_control_execution_worker_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_ag_artifact_retention_scheduler_daemon_operator_control_execution_worker_result_read_model_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s61_ae_operator_control_execution_worker_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_operator_control_execution_worker_result_persistence_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_s62_ae_worker_result_persistence_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_note_export_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_note_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_redacted_evidence_export_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s63_operator_review_evidence_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_workbench_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_workbench_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_workbench_privacy_regression.py --summary
"$PYTHON_BIN" scripts/smoke/run_s64_operator_review_workbench_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_case_action_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_case_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s65_operator_review_case_action_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_case_workbench_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_case_workbench_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_case_workbench_privacy_regression.py --summary
"$PYTHON_BIN" scripts/smoke/run_s66_operator_review_case_workbench_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_case_evidence_admission_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_case_evidence_admission_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_case_evidence_admission_privacy_regression.py --summary
"$PYTHON_BIN" scripts/smoke/run_s67_operator_review_case_evidence_admission_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_case_decision_lifecycle_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_case_lifecycle_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s68_operator_review_case_decision_lifecycle_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_case_sla_escalation_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_case_sla_escalation_privacy_regression.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_case_sla_escalation_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s69_operator_review_case_sla_escalation_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_action_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_privacy_regression.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s70_operator_review_escalation_action_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_outbound_dispatch_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_privacy_regression.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s71_operator_review_escalation_dispatch_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_execution_worker_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_execution_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s72_operator_review_escalation_dispatch_execution_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_live_provider_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_live_provider_privacy_regression.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_provider_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s73_operator_review_escalation_dispatch_provider_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_live_http_transport_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_notification_loopback_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_incident_loopback_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_live_http_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s74_operator_review_escalation_dispatch_live_http_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_privacy_regression.py --summary
"$PYTHON_BIN" scripts/smoke/run_s75_operator_review_escalation_dispatch_daemon_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_api_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_api_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_api_privacy_regression.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_api_runbook_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_api_admission_guard_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_s76_operator_review_escalation_dispatch_daemon_api_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_operations_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_operations_privacy_runbook_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_s77_operator_review_escalation_dispatch_daemon_operations_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_process_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_process_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_process_privacy_runbook_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_s78_operator_review_escalation_dispatch_daemon_process_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_liveness_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_liveness_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_liveness_privacy_runbook_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_s79_operator_review_escalation_dispatch_daemon_liveness_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_liveness_recovery_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_liveness_recovery_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_liveness_recovery_privacy_runbook_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_s80_operator_review_escalation_dispatch_daemon_liveness_recovery_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_liveness_ack_suppression_state_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_liveness_ack_state_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_operator_review_escalation_dispatch_daemon_liveness_ack_state_privacy_runbook_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_s81_operator_review_escalation_dispatch_daemon_liveness_ack_state_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_dispatch_liveness_ack_expiry_reconciliation_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_dispatch_liveness_ack_expiry_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_dispatch_liveness_ack_expiry_privacy_runbook_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_s82_ag_dispatch_liveness_ack_expiry_reconciliation_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_ack_expiry_automation_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_ack_expiry_automation_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_ack_expiry_automation_privacy_runbook_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_s83_ag_ack_expiry_automation_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_recovery_notification_policy_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_recovery_notification_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_recovery_notification_privacy_runbook_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_s84_ag_recovery_notification_policy_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_recovery_notification_delivery_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_recovery_notification_delivery_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_recovery_notification_delivery_privacy_runbook_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_s85_ag_recovery_notification_delivery_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_recovery_notification_live_delivery_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_recovery_notification_live_loopback_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_recovery_notification_live_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_recovery_notification_live_privacy_runbook_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_s86_ag_recovery_notification_live_delivery_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_audit_integrity_evidence_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_audit_evidence_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_resilience_performance_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_resilience_performance_privacy_runbook_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_audit_evidence_privacy_runbook_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_s87_ag_audit_integrity_evidence_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_resilience_performance_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_s88_ag_resilience_performance_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_audit_retention_archive_purge_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_audit_retention_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_audit_retention_privacy_runbook_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_s89_ag_audit_retention_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_mvp_acceptance_cx_transition_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_mvp_acceptance_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_mvp_acceptance_privacy_runbook_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_s90_ag_mvp_acceptance_cx_transition_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_current_state_reaudit_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_capability_traceability_inventory.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_persistence_gap_rebaseline.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_private_payload_boundary_decision.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_ownership_enforcement_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_runtime_coupling_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_database_drift_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_contract_api_drift_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_current_state_postgres_reaudit.py --summary
"$PYTHON_BIN" scripts/smoke/run_s91_cx_current_state_reaudit_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_private_content_ownership_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_access_context_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_central_authorization_enforcement.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_private_content_capability_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_private_text_store_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_private_vector_store_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_owner_lineage_persistence_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_api_contract_ownership_hardening.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_private_ownership_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s92_cx_private_content_ownership_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_durable_ingestion_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_ingestion_orchestration_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_ingestion_run_repository_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_durable_ingestion_admission_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_ingestion_checkpoint_coordinator_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_ingestion_worker_retry_recovery_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_ingestion_restart_read_model_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_ingestion_operations_contract_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_ingestion_operations_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s93_cx_durable_ingestion_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_vector_storage_freshness_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_vector_index_freshness_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_vector_persistence_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_pgvector_adapter_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_vector_atomic_publish_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_vector_reconciliation_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_vector_retrieval_guard_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_vector_readiness_api_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_vector_live_embedding_pgvector_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s94_cx_vector_storage_freshness_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_permission_hybrid_retrieval_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_retrieval_permission_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_lexical_candidate_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_fresh_vector_candidate_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_permission_first_hybrid_orchestration.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_weighted_rrf_rerank_privacy_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_hybrid_retrieval_package_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_retrieval_operations_observability.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_permission_hybrid_live_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s95_cx_permission_hybrid_retrieval_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_document_intelligence_similarity_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_document_intelligence_summary_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_document_summary_storage_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_document_summary_generation_adapter.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_summary_vector_pgvector.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_summary_similarity_adapter.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_document_intelligence_orchestration.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_document_intelligence_contract_observability.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_document_intelligence_live_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s96_cx_document_intelligence_summary_similarity_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_grounded_generation_runtime_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_grounded_generation_live_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s97_cx_grounded_generation_runtime_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_worker_operations_resilience_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_worker_operations_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s98_cx_worker_operations_resilience_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_async_generation_recovery_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_async_generation_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s99_cx_async_generation_recovery_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_mvp_integration_ae_handoff_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_mvp_integration_live_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s100_cx_mvp_integration_ae_handoff_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_current_state_reaudit_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_capability_traceability_inventory.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_persistence_gap_rebaseline.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_auth_ownership_privacy_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_runtime_coupling_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_database_drift_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_contract_api_drift_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_runtime_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_current_state_postgres_reaudit.py --summary
"$PYTHON_BIN" scripts/smoke/run_s101_ae_current_state_reaudit_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_durable_workspace_chat_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_workspace_chat_owner_scope_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_workspace_schema_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_workspace_repository_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_owner_scoped_workspace_api.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_owner_scoped_chat_api.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_durable_workspace_chat_orchestration.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_workspace_chat_contract_observability.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_workspace_chat_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s102_ae_durable_workspace_chat_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_intent_template_policy_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_intent_execution_mode_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_prompt_registry_sqlite.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_runtime_policy_resolver.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_runtime_policy_api.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_generation_policy_package.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_chat_runtime_policy.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_runtime_policy_contract_observability.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_runtime_policy_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s103_ae_runtime_policy_orchestration_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_cx_async_generation_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s104_ae_cx_async_generation_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_generation_lifecycle_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s105_ae_generation_lifecycle_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_citation_repair_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s106_ae_citation_repair_workflow_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_generated_response_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s107_ae_generated_response_lineage_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_async_artifact_render_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s108_ae_async_artifact_rendering_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_grounded_generation_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_grounded_generation_playwright_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s109_ae_web_grounded_generation_experience_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_mvp_acceptance_postgres_live_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_mvp_acceptance_privacy_runbook_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_s110_ae_mvp_acceptance_operations_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_current_state_reaudit_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_capability_traceability_inventory.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_catalog_config_drift_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_runtime_coupling_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_profile_privacy_refactor_checkpoint.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_precision_resource_safety_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_contract_api_drift_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_resilience_telemetry_readiness_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_s111_mo_current_state_reaudit_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_runtime_hardening_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_projection_extraction.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_catalog_extraction.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_normalization_extraction.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_transport_extraction.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_telemetry_extraction.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_registry_decoupling.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_runtime_hardening_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_operations_compatibility.py --summary
"$PYTHON_BIN" scripts/smoke/run_s112_mo_provider_runtime_operations_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_readiness_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_readiness_domain.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_readiness_plan.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_readiness_evaluator.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_readiness_cache.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_readiness_service.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_ready_route.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_route_health_api.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_readiness_live_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s113_mo_provider_readiness_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_contract_api_closure_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_canonical_api_contract_schemas.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_contract_fixture_completion.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_openapi_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_job_control_openapi_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_log_retention_openapi_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_runtime_openapi_parity_guard.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_contract_http_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_contract_api_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s114_mo_contract_api_drift_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_resilience_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_retry_policy.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_retry_executor.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_retry_transport.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_retry_wiring.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_retry_telemetry.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_resilience_composition.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_retry_loopback_http_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_resilience_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_s115_mo_provider_resilience_retry_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_telemetry_persistence_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_telemetry_persistence_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_telemetry_repository.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_telemetry_store.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_telemetry_runtime.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_telemetry_restart_concurrency.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_telemetry_durable_api.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_telemetry_durability_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_provider_telemetry_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s116_mo_durable_provider_telemetry_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_runtime_observability_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_runtime_observability_domain.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_runtime_observation_plan.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_runtime_observation_collector.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_runtime_observability_service.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_runtime_observability_api.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_runtime_observability_policy.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_runtime_observability_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_runtime_observability_live_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s117_mo_gpu_model_runtime_observability_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_catalog_lifecycle_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_catalog_lifecycle_domain.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_catalog_lifecycle_repository.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_catalog_lifecycle_service.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_alias_lifecycle.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_catalog_lifecycle_api.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_catalog_route_resolution.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_catalog_lifecycle_contracts.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_catalog_lifecycle_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s118_mo_catalog_alias_lifecycle_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_operations_integration_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_operations_snapshot_domain.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_operations_integration_service.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_operations_api.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_operations_acceptance_plan.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_operations_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_operations_integrated_acceptance.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_operations_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_operations_live_acceptance.py --summary
"$PYTHON_BIN" scripts/smoke/run_s119_mo_operations_integration_acceptance_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_mvp_acceptance_oa_transition_boundary_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_mvp_acceptance_policy.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_mvp_evidence_inventory.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_mvp_acceptance_evaluator.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_mvp_acceptance_api.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_mvp_acceptance_contracts.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_mvp_oa_transition_handoff.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_mvp_acceptance_postgres_live_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_mvp_acceptance_privacy_runbook_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_s120_mo_mvp_acceptance_oa_transition_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_current_state_reaudit_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_capability_traceability_inventory.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_database_drift_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_identity_lifecycle_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_credential_session_security_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_contract_api_drift_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_trust_coupling_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_projection_privacy_refactor_checkpoint.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_current_state_postgres_reaudit.py --summary
"$PYTHON_BIN" scripts/smoke/run_s121_oa_current_state_reaudit_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_identity_membership_lifecycle_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_subject_lifecycle_domain.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_membership_lifecycle_domain.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_identity_lifecycle_repository.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_subject_lifecycle_api.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_membership_lifecycle_api.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_deprovision_session_cascade.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_identity_lifecycle_contracts.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_identity_lifecycle_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s122_oa_identity_membership_lifecycle_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_credential_session_security_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_argon2_adaptive_rehash.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_atomic_login_lockout.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_security_persistence_migration.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_secure_session_lifecycle.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_credential_rotation.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_auth_event_flow.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_credential_security_contracts.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_credential_security_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s123_oa_credential_session_security_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_group_role_authorization_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_group_role_authorization_domain.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_authorization_persistence_migration.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_authorization_repository.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_effective_authorization_session.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_authorization_admin_api.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_authorization_scope_hardening.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_authorization_contracts.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_authorization_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s124_oa_group_role_authorization_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_production_trust_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_token_surface_inventory.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_production_token_profiles.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_signing_key_policy.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_token_validation_checkpoint.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_service_principal_handoff.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_token_rollout_plan.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_trust_threat_contracts.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_trust_postgres_baseline.py --summary
"$PYTHON_BIN" scripts/smoke/run_s125_oa_production_trust_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_service_principal_lifecycle_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_service_principal_migration.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_service_principal_contracts.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_service_principal_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s126_oa_service_principal_lifecycle_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_signed_token_lifecycle_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_signed_token_domain.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_signed_token_migration.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_signed_token_repository.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_signing_key_service.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_token_exchange.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_token_validation.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_signed_token_api.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_signed_token_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s127_oa_signed_token_lifecycle_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_signed_token_adoption_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_signed_token_verifier.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_service_token_admission.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_signed_token_adoption.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_signed_token_adoption.py --summary
"$PYTHON_BIN" scripts/smoke/run_mo_signed_token_adoption.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_signed_token_adoption.py --summary
"$PYTHON_BIN" scripts/smoke/run_service_token_rollout_observability.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_signed_token_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s128_platform_signed_token_adoption_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_federated_auth_ag_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_federated_identity_domain.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_federated_identity_persistence.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_oidc_verifier.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_federated_login_orchestration.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_federated_operator_context.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_federated_authorization_hardening.py --summary
"$PYTHON_BIN" scripts/smoke/run_s129_contract_runtime_privacy.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_federated_postgres_loopback_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s129_federated_auth_ag_integration_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_mvp_acceptance_platform_trust_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_signed_token_failure_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_mvp_acceptance_policy_traceability.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_identity_session_authorization_restart_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_key_rotation_restart_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_revocation_introspection_restart_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_cross_service_trust_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_mvp_contract_privacy_runbook.py --summary
"$PYTHON_BIN" scripts/smoke/run_s130_oa_mvp_platform_trust_acceptance.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_artifact_lifecycle_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_artifact_lifecycle_playwright_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s46_ae_artifact_lifecycle_management_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_remediation_execution_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_remediation_execution_read_model_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s130_oa_mvp_platform_trust_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_vertical_spine_reaudit_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_route_client_topology_inventory.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_runtime_profile_residue_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_oa_ae_trust_path_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_ae_cx_integration_path_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_cx_mo_provider_path_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_ae_artifact_ag_audit_path_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_persistence_worker_process_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_contract_trace_privacy_e2e_gap_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_s131_platform_vertical_spine_reaudit_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_runtime_topology_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_runtime_manifest_domain.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_runtime_profile_composition.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_runtime_dependency_graph.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_endpoint_timeout_policy.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_complete_process_manifest.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_ag_projection_policy.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_runtime_orchestrator.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_local_mock_process_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s132_platform_runtime_topology_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_postgres_restart_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_postgres_restart_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_postgres_test_targets.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_test_migration_readiness.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_postgres_pool_lifecycle.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_test_profile_startup.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_postgres_restart_state_machine.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_postgres_restoration.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_postgres_restart_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s133_platform_postgres_restart_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_oa_backed_trust_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_trust_evidence.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_trust_scope_policy.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_trust_restart_plan.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_trust_operations_hardening.py --summary
"$PYTHON_BIN" scripts/smoke/run_s134_platform_oa_backed_trust_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_authenticated_document_ingestion_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_protected_upload_owner_policy.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_upload_handoff_persistence.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_upload_admission_lineage.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_ingestion_worker_hydration.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_mock_vector_publish_freshness.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_upload_ingestion_progress.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_ingestion_restart_cancellation.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_authenticated_ingestion_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s135_authenticated_document_ingestion_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_permission_hybrid_retrieval_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_permission_first_scope_hardening.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_current_chunk_candidate_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_live_retrieval_provider_identity.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_weighted_rrf_acceptance.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_retrieval_confidence_acceptance.py --summary
"$PYTHON_BIN" scripts/smoke/run_s136_model_calibration_live.py --summary
"$PYTHON_BIN" scripts/smoke/run_s136_permission_hybrid_live_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s136_permission_hybrid_retrieval_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_grounded_generation_artifact_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_retrieval_package_materialization.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_grounded_generation_runtime_composition.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_grounding_repair_lineage.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_grounded_response_lineage.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_grounded_artifact_admission.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_grounded_artifact_recovery_access.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_grounded_generation_artifact_e2e.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_grounded_generation_artifact_live_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s137_grounded_generation_artifact_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_ag_cross_service_trace_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_trace_envelope_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_cx_trace_projection_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_trace_projection_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_mo_trace_projection_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_cross_service_trace_aggregation_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_cross_service_trace_operations_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_ag_cross_service_trace_deterministic_e2e.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_ag_trace_postgres_smoke.py --summary
"$PYTHON_BIN" scripts/smoke/run_s138_ag_cross_service_trace_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_korean_golden_journey_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_korean_message_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_golden_journey_state.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_login_upload_ingestion_acceptance.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_grounding_journey_acceptance.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_artifact_journey_acceptance.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_viewport_accessibility_acceptance.py --summary
"$PYTHON_BIN" scripts/smoke/run_ae_web_korean_golden_journey_playwright_acceptance.py --summary
"$PYTHON_BIN" scripts/smoke/run_s139_ae_web_protected_acceptance.py --summary
"$PYTHON_BIN" scripts/smoke/run_s139_ae_web_korean_golden_journey_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_mvp_release_candidate_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_release_candidate_gate_matrix.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_generation_golden_scenarios.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_release_candidate_admission.py --sample --summary
"$PYTHON_BIN" scripts/smoke/run_platform_release_candidate_postgres_restart.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_release_candidate_live_providers.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_release_candidate_browser_ag_operations.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_release_candidate_assurance.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_release_candidate_protected_matrix.py --summary
"$PYTHON_BIN" scripts/smoke/run_s140_platform_release_candidate_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_production_readiness_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_production_deferral_inventory.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_nonproduction_path_inventory.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_production_configuration_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_runtime_deployment_coupling_audit.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_production_responsibility_matrix.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_operational_incompleteness_register.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_production_transition_dependency_plan.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_production_evidence_decision_contract.py --summary
"$PYTHON_BIN" scripts/smoke/run_s141_platform_production_readiness_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_deployment_packaging_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_deployment_artifact_catalog.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_deployment_build_inputs.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_oci_build_definitions.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_packaged_entrypoints.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_environment_compositions.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_packaged_lifecycle.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_deployment_provenance.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_packaged_runtime_acceptance.py --summary
"$PYTHON_BIN" scripts/deployment/build_platform_images.py --summary
"$PYTHON_BIN" scripts/smoke/run_s142_platform_deployment_packaging_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_production_security_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_production_configuration_manifest.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_production_startup_admission.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_production_secret_materialization.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_production_secret_rotation.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_production_api_key_custody.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_production_tls_lifecycle.py --summary
"$PYTHON_BIN" scripts/smoke/run_platform_production_security_local_rehearsal.py --summary
"$PYTHON_BIN" scripts/smoke/run_s143_external_staging_acceptance.py --summary
"$PYTHON_BIN" scripts/smoke/run_s143_production_configuration_secret_tls_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_s144_oa_production_trust_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_openbao_transit_signer.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_openbao_transit_runtime.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_openbao_transit_key_lifecycle.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_openbao_transit_rotation_checkpoint.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_enterprise_oidc_registration.py --summary
"$PYTHON_BIN" scripts/smoke/run_oa_oidc_rollover_resilience.py --summary
"$PYTHON_BIN" scripts/smoke/run_s144_staging_trust_rehearsal.py --summary
"$PYTHON_BIN" scripts/smoke/run_s144_protected_trust_federation_acceptance.py --summary
"$PYTHON_BIN" scripts/smoke/run_s144_oa_production_trust_closure.py --summary
"$PYTHON_BIN" scripts/smoke/run_s145_postgresql_resilience_boundary.py --summary
"$PYTHON_BIN" scripts/smoke/run_s145_postgresql_backup_policy.py --summary
